### ISSUE TITLE
ROCM Cuda not available

### ISSUE THREAD

**Issue by ironstarfish** [ublue-os/bazzite#1044]
### Describe the bug

Trying to run pytorch with CUDA. Can only run on CPU.
AMD GPU detected using rocminfo.
Tried to install rocm components on top, still get the issue.

### What did you expect to happen?

CUDA capabilities enabled.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:1a7a9e5229cfe2ba234ba78292c411b3d53755f39dfe1fa77239e8367c745f2a
                  Version: 40.20240427.0 (2024-04-27T22:34:27Z)
          LayeredPackages: bpytop htop rclone rocm-clinfo rocm-hip rocm-opencl
            LocalPackages: lact-libadwaita-0.5.4-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:1a7a9e5229cfe2ba234ba78292c411b3d53755f39dfe1fa77239e8367c745f2a
                  Version: 40.20240427.0 (2024-04-27T22:34:27Z)
          LayeredPackages: bpytop htop rclone
            LocalPackages: lact-libadwaita-0.5.4-0.x86_64
```

### Hardware

X470 AORUS GAMING 7 WIFI
Ryzen 5800X
Radeon 6900XT

**Comment by KyleGospo** [comment]
ROCM is definitely working here on the same GPU. I would try unlayering all of that with `rpm-ostree reset`, and then running pytorch via distrobox with ROCM's libraries installed in the box.

**Comment by ironstarfish** [comment]
> ROCM is definitely working here on the same GPU. I would try unlayering all of that with `rpm-ostree reset`, and then running pytorch via distrobox with ROCM's libraries installed in the box.

This worked for me. Thanks!
